# SPDX-FileCopyrightText: 2022 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
# Default values for xmitd-talaria.

talaria:
  # docker image used
  image: xmidt/talaria
  address:
    host: ""
    port: "6200"

health:
  address:
    host: ""
    port: "6201"

pprof:
  address:
    host: ""
    port: "6202"

control:
  address:
    host: ""
    port: "6203"

metric:
  address:
    host: ""
    port: "6204"  

# Pull secret used when images are stored in a private repository
# imagePullSecretName:


